services:
  - type: web
    name: mis-gastos
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
